ALTER TABLE ROLES ADD CONSTRAINT pk_roles PRIMARY KEY (role_id);
ALTER TABLE ROLES ADD CONSTRAINT uq_role_name UNIQUE (role_name);

ALTER TABLE USERS ADD CONSTRAINT pk_users PRIMARY KEY (user_id);
ALTER TABLE USERS ADD CONSTRAINT uq_user_email UNIQUE (email);
ALTER TABLE USERS ADD CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES ROLES(role_id);
ALTER TABLE USERS ADD CONSTRAINT chk_user_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'));

ALTER TABLE WALLETS ADD CONSTRAINT pk_wallets PRIMARY KEY (wallet_id);
ALTER TABLE WALLETS ADD CONSTRAINT uq_wallet_user UNIQUE (user_id);
ALTER TABLE WALLETS ADD CONSTRAINT fk_wallets_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE;
ALTER TABLE WALLETS ADD CONSTRAINT chk_wallet_balance CHECK (balance >= 0);

ALTER TABLE TOKEN_TRANSFERS ADD CONSTRAINT pk_transfers PRIMARY KEY (transfer_id);
ALTER TABLE TOKEN_TRANSFERS ADD CONSTRAINT fk_transfer_sender FOREIGN KEY (sender_wallet_id) REFERENCES WALLETS(wallet_id);
ALTER TABLE TOKEN_TRANSFERS ADD CONSTRAINT fk_transfer_receiver FOREIGN KEY (receiver_wallet_id) REFERENCES WALLETS(wallet_id);
ALTER TABLE TOKEN_TRANSFERS ADD CONSTRAINT chk_transfer_amount CHECK (amount > 0);
ALTER TABLE TOKEN_TRANSFERS ADD CONSTRAINT chk_transfer_status CHECK (status IN ('COMPLETED', 'FAILED', 'PENDING'));
ALTER TABLE TOKEN_TRANSFERS ADD CONSTRAINT chk_different_wallets CHECK (sender_wallet_id <> receiver_wallet_id);

ALTER TABLE TRANSACTIONS ADD CONSTRAINT pk_transactions PRIMARY KEY (transaction_id);
ALTER TABLE TRANSACTIONS ADD CONSTRAINT fk_tx_wallet FOREIGN KEY (wallet_id) REFERENCES WALLETS(wallet_id);
ALTER TABLE TRANSACTIONS ADD CONSTRAINT chk_tx_type CHECK (transaction_type IN ('CREDIT', 'DEBIT', 'DEPOSIT', 'WITHDRAWAL'));
ALTER TABLE TRANSACTIONS ADD CONSTRAINT chk_tx_amount CHECK (amount > 0);
ALTER TABLE TRANSACTIONS ADD CONSTRAINT chk_tx_status CHECK (status IN ('COMPLETED', 'FAILED', 'PENDING'));

ALTER TABLE AUDIT_LOG ADD CONSTRAINT pk_audit_log PRIMARY KEY (audit_id);
ALTER TABLE AUDIT_LOG ADD CONSTRAINT chk_audit_op CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE'));
