DROP SEQUENCE role_seq;
DROP SEQUENCE user_seq;
DROP SEQUENCE wallet_seq;
DROP SEQUENCE transfer_seq;
DROP SEQUENCE transaction_seq;
DROP SEQUENCE audit_seq;

CREATE SEQUENCE role_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE user_seq START WITH 101 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE wallet_seq START WITH 501 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE transfer_seq START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE transaction_seq START WITH 5001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE audit_seq START WITH 9001 INCREMENT BY 1 NOCACHE;
