SET SERVEROUTPUT ON;

-- Test invalid user
BEGIN
    TRANSFER_TOKENS(9999, 102, 100);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

-- Test insufficient balance
BEGIN
    TRANSFER_TOKENS(104, 102, 50000);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

-- Test invalid amount
BEGIN
    TRANSFER_TOKENS(101, 102, -50);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

-- Test same user
BEGIN
    TRANSFER_TOKENS(101, 101, 100);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/
